from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('what-we-do/', views.what_we_do, name='what_we_do'),
    path('governance/', views.governance, name='governance'),
    path('board-members/', views.board_members, name='board_members'),
    path('board-committees/', views.board_committees, name='board_committees'),
    path('ceo-and-executive-team/', views.ceo_and_executive_team, name='ceo_and_executive_team'),
    path('donors-and-supporters/', views.donors_and_supporters, name='donors_and_supporters'),
    path('get-help/', views.get_help, name='get_help'),
    path('join-teen-club/', views.join_teen_club, name='join_teen_club'),
    path('child-clinic/', views.child_clinic, name='child_clinic'),
    path('hiv-services/', views.hiv_services, name='hiv_services'),
    path('pmtct/', views.pmtct, name='pmtct'),
    path('volunteer/', views.volunteer, name='volunteer'),
    path('youth/', views.youth, name='youth'),
    path('fundraise/', views.fundraise, name='fundraise'),
    path('corporate/', views.corporate, name='corporate'),
    path('health/', views.health, name='health'),
    path('livelihood/', views.livelihood, name='livelihood'),
    path('community-empowerment/', views.community_empowerment, name='community_empowerment'),
    path('youth-empowerment/', views.youth_empowerment, name='youth_empowerment'),
    path('education/', views.education, name='education'),
    path('donate/specific-program/', views.specific_program, name='specific_program'),
    path('donate/general-programs/', views.general_program, name='general_program'),
    path('donate/child/', views.donate_child, name='donate_child'),
    path('support/in-kind/', views.in_kind, name='in_kind'),
    path('hiv-aids/about/', views.about_hiv, name='about_hiv'),
    path('hiv-aids/malawi-statistics/', views.malawi_statistics, name='malawi_statistics'),
    path('hiv-aids/basic-facts/', views.basic_facts, name='basic_facts'),
    path('hiv-aids/world-statistics/', views.world_hiv_statistics, name='world_hiv_statistics'),
    path('donate/', views.donate, name='donate'),
    path('donate/success/', views.donate_success, name='donate_success'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('subscribe/', views.subscribe, name='subscribe'),  # Added
    path('webhook/paychangu/', views.paychangu_webhook, name='paychangu_webhook'),
]