# Generated by Django 5.1.7 on 2025-03-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clinic_visits', models.IntegerField(default=0)),
                ('vaccinations', models.IntegerField(default=0)),
                ('other_interventions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distribution_type', models.CharField(choices=[('FOOD', 'Food'), ('LIKUNI_PHALA', 'Likuni Phala'), ('CLOTHES', 'Clothes'), ('SCHOOL_ITEMS', 'School Items'), ('SCHOOL_FEES', 'School Fees'), ('LIVESTOCK', 'Livestock'), ('FARM_INPUTS', 'Farm Inputs'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('recipient_count', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMTCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked', models.IntegerField(default=0)),
                ('attendance_breastfeeding', models.IntegerField(default=0)),
                ('attendance_antenatal', models.IntegerField(default=0)),
                ('due_dbs', models.IntegerField(default=0)),
                ('missed', models.IntegerField(default=0)),
                ('hiv_positive', models.IntegerField(default=0)),
                ('hiv_negative', models.IntegerField(default=0)),
                ('newly_enrolled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeenClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked', models.IntegerField(default=0)),
                ('attendance_male', models.IntegerField(default=0)),
                ('attendance_female', models.IntegerField(default=0)),
                ('missed', models.IntegerField(default=0)),
                ('samples_high_viral', models.IntegerField(default=0)),
                ('samples_ldl', models.IntegerField(default=0)),
                ('malnutrition_moderate', models.IntegerField(default=0)),
                ('malnutrition_severe', models.IntegerField(default=0)),
                ('referrals_psychosocial', models.IntegerField(default=0)),
                ('referrals_clinic', models.IntegerField(default=0)),
                ('referrals_other', models.IntegerField(default=0)),
                ('newly_enrolled', models.IntegerField(default=0)),
                ('graduated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
