# Generated by Django 5.1.7 on 2025-03-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IECMaterialDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_unit', models.CharField(default='TA Mwaulambya', max_length=100)),
                ('data_set', models.CharField(default='LAHARS 1.1 IEC Material Distribution (Print)', max_length=100)),
                ('period', models.CharField(default='January 2025', max_length=50)),
                ('implementing_partner', models.CharField(default='Light House Trust', max_length=100)),
                ('distributes_iec', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posters_facilities_prevention', models.IntegerField(default=0)),
                ('posters_facilities_care', models.IntegerField(default=0)),
                ('posters_facilities_impact', models.IntegerField(default=0)),
                ('posters_facilities_rssh', models.IntegerField(default=0)),
                ('posters_communities_prevention', models.IntegerField(default=0)),
                ('posters_communities_care', models.IntegerField(default=0)),
                ('posters_communities_impact', models.IntegerField(default=0)),
                ('posters_communities_rssh', models.IntegerField(default=0)),
                ('posters_hotspots_prevention', models.IntegerField(default=0)),
                ('posters_hotspots_care', models.IntegerField(default=0)),
                ('posters_hotspots_impact', models.IntegerField(default=0)),
                ('posters_hotspots_rssh', models.IntegerField(default=0)),
                ('pamphlets_facilities_prevention', models.IntegerField(default=0)),
                ('pamphlets_facilities_care', models.IntegerField(default=0)),
                ('pamphlets_facilities_impact', models.IntegerField(default=0)),
                ('pamphlets_facilities_rssh', models.IntegerField(default=0)),
                ('pamphlets_communities_prevention', models.IntegerField(default=0)),
                ('pamphlets_communities_care', models.IntegerField(default=0)),
                ('pamphlets_communities_impact', models.IntegerField(default=0)),
                ('pamphlets_communities_rssh', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
