# Generated by Django 5.1.7 on 2025-04-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_attendance_antenatal_pmtct_hiv_exposed_infants_art_prophylaxis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('airtel_money', 'Airtel Money'), ('tnm_mpamba', 'TNM Mpamba')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinichealthrecord',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='educationrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='iecmaterialdistribution',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='itemdistribution',
            name='staff',
        ),
        migrations.DeleteModel(
            name='JobOpening',
        ),
        migrations.RemoveField(
            model_name='patienthealthrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='pmtct',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='teenclub',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='youthrecord',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='ClinicHealthRecord',
        ),
        migrations.DeleteModel(
            name='EducationRecord',
        ),
        migrations.DeleteModel(
            name='IECMaterialDistribution',
        ),
        migrations.DeleteModel(
            name='ItemDistribution',
        ),
        migrations.DeleteModel(
            name='PatientHealthRecord',
        ),
        migrations.DeleteModel(
            name='PMTCT',
        ),
        migrations.DeleteModel(
            name='TeenClub',
        ),
        migrations.DeleteModel(
            name='YouthRecord',
        ),
    ]
