# Generated by Django 5.1.7 on 2025-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmessage_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_purpose',
            field=models.CharField(choices=[('child', 'Donate for a Child'), ('specific_program', 'Donate for a Specific Program'), ('general_program', 'Donate for a Program'), ('general', 'General Donation')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='specific_program',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('MWK', 'Malawi Kwacha'), ('USD', 'US Dollar')], default='MWK', max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('airtel_money', 'Airtel Money'), ('tnm_mpamba', 'TNM Mpamba'), ('card', 'Credit/Debit Card')], max_length=50),
        ),
    ]
