# Generated by Django 5.0.11 on 2025-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_donation_donation_purpose_donation_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
