# Generated by Django 5.0.11 on 2025-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_blogpost_date_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The main quote or testimonial text (the story).')),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial.', max_length=100)),
                ('author_relation', models.CharField(blank=True, help_text="Relation to Thembi (e.g., 'Bursary Recipient').", max_length=150)),
                ('author_image', models.ImageField(blank=True, help_text='Optional: Upload a picture of the author.', null=True, upload_to='testimonials/')),
                ('feature_on_homepage', models.BooleanField(db_index=True, default=False, help_text='Check to feature this testimonial on the homepage.')),
                ('related_program_info', models.CharField(blank=True, help_text='Optional: Mention the specific program.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial / Success Story',
                'verbose_name_plural': 'Testimonials / Success Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
